---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    hajimari:
      title: Apps
      darkTheme: tron
      lightTheme: lime
      alwaysTargetBlank: true
      showGreeting: false
      showAppGroups: false
      showAppStatus: false
      showBookmarkGroups: false
      showGlobalBookmarks: false
      showAppUrls: false
      defaultEnable: true
      defaultSearchProvider: Startpage
      searchProviders:
        - name: Startpage
          token: sp
          icon: mdi:source-commit-start
          searchUrl: https://www.startpage.com/sp/search?query={query}&abp=-1&t=night&lui=english&sc=40fZen0iNfbb20&cat=web&prfe=91999b25d02ee3576b56678b7b1d164fa7f919f3f511d3e820849bfbf2a8d1e5ebc386cb6f514123340a63a4ae5e50698a6466ede6ff3c3bc59d5a604879b33a907512645f53863b16297bcf42
          url: https://www.startpage.com
        - name: Google
          token: g
          icon: simple-icons:google
          searchUrl: https://www.google.com/search?q={query}
          url: https://www.google.com
        - name: DuckDuckGo
          token: d
          icon: simple-icons:duckduckgo
          searchUrl: https://duckduckgo.com/?q={query}
          url: https://duckduckgo.com
        - name: IMDB
          token: i
          icon: simple-icons:imdb
          searchUrl: https://www.imdb.com/find?q={query}
          url: https://www.imdb.com
        - name: Reddit
          token: r
          icon: simple-icons:reddit
          searchUrl: https://www.reddit.com/search?q={query}
          url: https://www.reddit.com
        - name: YouTube
          token: 'y'
          icon: simple-icons:youtube
          searchUrl: https://www.youtube.com/results?search_query={query}
          url: https://www.youtube.com
        - name: Spotify
          token: s
          icon: simple-icons:spotify
          searchUrl: hhttps://open.spotify.com/search/{query}
          url: https://open.spotify.com
      namespaceSelector:
        matchNames:
          - default
          - monitoring
          - networking
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: |
            10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
          hajimari.io/enable: "false"
        hosts:
          - host: &host "hajimari.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podAnnotations:
      configmap.reloader.stakater.com/reload: hajimari-settings
    persistence:
      data:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 100m
        memory: 128M
