---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-gitlab-runner
  namespace: flux-system
spec:
  path: ./kubernetes/apps/default/gitlab-runner/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: gitlab-runner
      namespace: default
  interval: 30m
  retryInterval: 1m
  timeout: 3m
