apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:V8yJ8ocDZHbNKbZ/Qts66VRqrNf0MCWkk6ypavRCv1sQPCNqUA==,iv:L1ZMwFweQpz/boUfqM2V5sO9LtxqAvEhHLjKH9AJ6NI=,tag:j9NOQIGoqGTmsK4NKVASLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sx2zwfenwsr5g6slh2mfaeydxjcxmhadxt8vm3hfgtzqhynwp4ssz4g83l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0OUl4NGpoMU1GODg1YUlr
            NGlFdThUT2tNTVNuSE1mV1NrMnU3bVZyS0MwCk84T0tvY3pJK2xmYmFCVU1VT3dJ
            dUNINmJiMVF3T1h2YkR0RThQYmVKQ1EKLS0tIEcyUTZ6QXQrdzdpaHRhblRDMzlh
            UzkyUVlKV0F3NjUvR3Q5Tk1XYk1LUGsKuI5bI4YNbesSvLqEAiybfsqSKY3StCoU
            NW6p5MTWahIgyGrigeOJCdjEeT+s/jG0Ad3tV6SrtWI0XaF0N2xlGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-02T14:25:02Z"
    mac: ENC[AES256_GCM,data:UkHaAiZw/eS3tpQthi7+X9QXHUafsNLOP/mmHwD7t7sReZUFIYtJW2R5gzu46zqh9r0j9CQulQScKYQsbclGuwUIvgiU8TClEQP+PO9bTp2EwCPnDDXM2QxJW+3ZpAKzJZQTyslqLZeYnyvxKz5J1rY+Ja42APn9RaJzHNWR0fU=,iv:5M2SouykClZQncFycVtnxEqfYE6vsXss19AJhjJ5OMI=,tag:3r1tSbldXJCxiHQ+Y3fV6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
